SELECT * FROM master_timeline
WHERE ---("time" > '2025-12-01' AND "time" < '2025-12-20') AND
description ILIKE ANY (ARRAY[
	'%TrackView%',
	'%Reptilic%',
	'%SpyPhone%',
	'%MobileTracker%',
	'%Cerberus%',
	'%Wspy%',
	'%Unisafe%',
	'%mSpy%',
	'%MonitorMinor%',
	'%KeyLog%',
	'%PhoneSheriff%',
	'%MobileSpy%',
	'%RetinaX%',
	'%Retina-X%',
	'%TeenShield%',
	'%TheTruthSpy%',
	'%iSpyoo%',
	'%PhoneSpector%',
	'%Spyera%',
	'%iKeyMonitor%',
	'%Mobistealth%',
	'%Spymie%',
	'%GuestSpy%',
	'%Spynote%',
	'%NeoSpy%',
	'%FlexiSpy%',
	'%Spy Master Pro%',
	'%SpyMasterPro%',
	'%SpyHuman%',
	'%Spyfone%',
	'%FamilyOrbit%',
	'%Family Orbit%',
	'%Copy9%',
	'%SpyBubble%',
	'%Android Spy%',
	'%AndroidSpy%',
	'%uMobix%',
	'%Catwatchful%',
	'%SpyX%',
	'%Cocospy%',
	'%pcTattletale%',
	'%Spyic%',
	'%Spyzie%',
	'%KidsGuard Pro%',
	'%KidsGuardPro%',
	'%Eyezy%'
])
ORDER BY "time"
